export const ARTICLE_REQUEST = "ARTICLE_REQUEST";
export const ARTICLE_SUCCESS = "ARTICLE_SUCCESS";
export const ARTICLE_FAILURE = " ARTICLE_FAILURE";
export const ARTICLE_RECEIVE = " ARTICLE_RECEIVE";
export const TAGLIST_RECEIVE = " TAGLIST_RECEIVE";
export const CHANGE_TAG = "CHANGE_TAG";
export const ARTICLE_DETAILE_RECEIVE = 'ARTICLE_DETAILE_RECEIVE'